### ISSUE TITLE
ChatGPTError: ChatGPT invalid session token

### ISSUE THREAD

**Issue by Gimlao** [BennyDeeDev/chatgpt-twitch-bot#2]
```
[04:31] info: Connecting to irc-ws.chat.twitch.tv on port 443..
[04:31] info: Sending authentication to server..
[04:31] info: Connected to server.
[04:31] info: Executing command: JOIN #
[04:31] error: No response from Twitch.
c:\Logiciels\chatgpt-twitch-bot-main\node_modules\chatgpt\build\index.js:526
      throw new ChatGPTError("ChatGPT invalid session token");
            ^


ChatGPTError: ChatGPT invalid session token
    at ChatGPTAPI (c:\Logiciels\chatgpt-twitch-bot-main\node_modules\chatgpt\build\index.js:526:13)
    at <anonymous> (c:\Logiciels\chatgpt-twitch-bot-main\chatgpt-twitch-bot.ts:27:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.13.0
```

**Comment by kooj** [comment]
I have the same issue.
